#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
  path: /
  controller: App\Controller\BeController::index

document_verif:
  path: /verif
  controller: App\Controller\BeController::verif

document_param:
  path: /param
  controller: App\Controller\BeController::param

autocad_import:
  path: /createSynoptique
  controller: App\Controller\AutocadController::import

regle:
  path: /regle
  controller: App\Controller\BeController::regle